_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
attack_bbox_max:
    value: 0.5,0.5,0.5
attack_bbox_min:
    value: -0.5,-0.5,-0.5
beta:
    value: 0.1
checkpoint_iterations:
    value: []
compute_cov3D_python:
    value: false
convert_SHs_python:
    value: false
data_device:
    value: cuda
debug:
    value: false
debug_from:
    value: -1
densification_interval:
    value: 100
densify_from_iter:
    value: 500
densify_grad_threshold:
    value: 0.0002
densify_until_iter:
    value: 15000
detect_anomaly:
    value: false
eval:
    value: true
feature_lr:
    value: 0.0025
images:
    value: images
ip:
    value: 127.0.0.1
iterations:
    value: 5000
kernel_size:
    value: 0.1
lambda_collapse:
    value: 1
lambda_dssim:
    value: 0.2
load_allres:
    value: false
model_path:
    value: /workspace/wwang/poison-splat/log/chair_trigger/checkerboard_bw
mu_vector:
    value: 0.0,0.0,0.0
opacity_lr:
    value: 0.05
opacity_reset_interval:
    value: 3000
percent_dense:
    value: 0.01
poison_config_path:
    value: null
poison_ratio:
    value: 0.05
port:
    value: 6009
position_lr_delay_mult:
    value: 0.01
position_lr_final:
    value: 1.6e-06
position_lr_init:
    value: 0.00016
position_lr_max_steps:
    value: 30000
quiet:
    value: false
ray_jitter:
    value: false
resample_gt_image:
    value: false
resolution:
    value: -1
rotation_lr:
    value: 0.001
sample_more_highres:
    value: false
save_iterations:
    value:
        - 5000
        - 5000
scaling_lr:
    value: 0.005
sh_degree:
    value: 3
source_path:
    value: /workspace/wwang/poison-splat/dataset/nerf_synthetic/chair
start_checkpoint:
    value: null
synthetic_trigger_type:
    value: checkerboard_bw
test_iterations:
    value:
        - 5000
trigger_path:
    value: /workspace/wwang/poison-splat/assets/triggers/checkerboard_bw_trigger.png
trigger_position:
    value: bottom_right
trigger_size:
    value: 64,64
trigger_type:
    value: synthetic
use_wandb:
    value: true
white_background:
    value: true
